import Head from 'next/head'
import { useRouter } from 'next/router'
import {useContext,useEffect } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ProfileContext } from '../context/profile'
import { AnimationContext } from '../context/Animation'

export default function Home() {
  const router = useRouter()
  const {handleAuth,profile,isAuthenticated} = useContext(ProfileContext)
  const {handleAnimation} = useContext(AnimationContext)

  const handelProfile = (profile) => {
    handleAuth(profile)
    router.push('/home')
    handleAnimation()
  }

  useEffect(()=>{
    // console.log(isAuthenticated)
    if(isAuthenticated){
      router.push('/home')
      handleAnimation()
    }
  },[isAuthenticated])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="main-content">
          <div className="main-title"> Who Watching ?</div>
          <div className="profile-wr">
              <div className="profile" onClick={() =>handelProfile(1)}>
                <img src="/profile-1.jpg" alt="" className="profile-icon" />
                <p> Person 1</p>
              </div>  
              <div className="profile" onClick={() =>handelProfile(2)}>
                <img src="/profile-2.jpg" alt="" className="profile-icon" />
                <p>   Person 2</p>

              </div>
              <div className="profile" onClick={() =>handelProfile(3)}>
                <img src="/profile-3.jpg" alt="" className="profile-icon" />
                <p> Person 3</p>
                
              </div>
              <div className="profile" onClick={() =>handelProfile(4)}>
                <img src="/profile-4.jpg" alt="" className="profile-icon" />
                <p> Person 4</p>

              </div>
          </div>
        </div>
      </main>
    </div>
  )
}
